name: Run Crypto Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"  # هر 30 دقیقه اجرا شود

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install ccxt pandas matplotlib mplfinance requests

    - name: Run script
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python main.py
