name: KuCoin Analyzer Bot

on:
  schedule:
    - cron: '*/30 * * * *'  # هر ۳۰ دقیقه اجرا شود
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install ccxt pandas mplfinance requests matplotlib

    - name: Run main script
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: python main.py
